language: php
sudo: required
dist: trusty
group: edge

php:
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
  - php: hhvm-nightly

before_script: composer install

script:
  - hh_server --check $(pwd)
  - vendor/bin/hacktest tests
