namespace Usox\HaRm\Writer;

use namespace Facebook\HackCodegen;

final class HarmCodegenConfig implements HackCodegen\IHackCodegenConfig {

    public function shouldUseTabs(): bool {
        return true;
    }

    public function getFileHeader(): vec<string> {
        return vec['Generated by HaRm'];
    }

    public function getSpacesPerIndentation(): int {
        return 4;
    }

    public function getMaxLineLength(): int {
        return 80;
    }

    public function getRootDir(): string {
        return __DIR__;
    }

    public function getFormatter(): ?HackCodegen\ICodegenFormatter {
        return null;
    }
}
